version: "3.6"
services:
  zip-symlink:
    build: ./zip-symlink
    volumes:
      - ./zip-symlink/src/:/var/www/html/
      - /var/www/html/upload
    ports:
      - 9091:80
  example-symlink:
    build: ./example-symlink
    volumes:
      - "./example-symlink/src:/var/www/html"
    ports:
      - 9090:80
